
ROOT_DIR	:= /root/cc1600sdk/mp4sdk/mp4sdk/
all :
	make -C $(ROOT_DIR)/MultiPlatform/lib/source/advlib/make-x690hd-gcc
	make -C $(ROOT_DIR)/MultiPlatform/lib/source/font/make-cc1600-gcc
	make -C $(ROOT_DIR)/MultiPlatform/lib/source/multimedia/make-cc1600-gcc
	make -C $(ROOT_DIR)/MultiPlatform/lib/source/xgui/make-x690hd-gcc
	make -C $(ROOT_DIR)/MultiPlatform/lib/source/graphics/make-cc1600-gcc
	make -C $(ROOT_DIR)/MultiPlatform/lib/source/miniio/make-cc1600-gcc
	make -C $(ROOT_DIR)/MultiPlatform/lib/source/SDL/make-cc1600-gcc
	make -C $(ROOT_DIR)/MultiPlatform/lib/source/stdpatch/make-x690hd-gcc
	make -C $(ROOT_DIR)/MultiPlatform/lib/source/zlib/make-cc1600-gcc



clean: 
	make -C $(ROOT_DIR)/MultiPlatform/lib/source/advlib/make-x690hd-gcc clean
	make -C $(ROOT_DIR)/MultiPlatform/lib/source/font/make-cc1600-gcc clean
	make -C $(ROOT_DIR)/MultiPlatform/lib/source/multimedia/make-cc1600-gcc clean
	make -C $(ROOT_DIR)/MultiPlatform/lib/source/xgui/make-x690hd-gcc clean
	make -C $(ROOT_DIR)/MultiPlatform/lib/source/graphics/make-cc1600-gcc clean
	make -C $(ROOT_DIR)/MultiPlatform/lib/source/miniio/make-cc1600-gcc clean
	make -C $(ROOT_DIR)/MultiPlatform/lib/source/SDL/make-cc1600-gcc clean
	make -C $(ROOT_DIR)/MultiPlatform/lib/source/stdpatch/make-x690hd-gcc clean
	make -C $(ROOT_DIR)/MultiPlatform/lib/source/zlib/make-cc1600-gcc clean

.PHONY: clean all
